branch-defaults:
  default:
    environment: Project3-env
environment-defaults:
  Testapp-env:
    branch: null
    repository: null
artifact: www/Archive.zip
global:
  application_name: Project3-env
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
